import type { ArtifactKind, CapabilityStatus } from '../domain/types';

/**
 * XSite agent operating system — typed catalog of all 26 agents.
 *
 * Agents exchange typed, versioned artifacts through structured workflow
 * contracts — never uncontrolled free-form messages. Each definition declares
 * the eleven mandatory fields required by the governance model. This catalog
 * seeds the `AgentDefinition` table and drives the agent runtime in Phase 2;
 * in Phase 1 the runtime status is honestly `planned`.
 */

export interface RetryPolicy {
  maxRetries: number;
  backoff: 'none' | 'linear' | 'exponential';
  /** Things that must never be retried automatically. */
  neverRetry: string[];
}

export interface AgentDefinition {
  key: string;
  name: string;
  responsibility: string;
  allowedInputs: string[];
  allowedOutputs: string[];
  /** Artifact kinds this agent may produce (workflow contract). */
  producesArtifacts: ArtifactKind[];
  permissionBoundaries: string[];
  requiredTools: string[];
  escalationConditions: string[];
  retryPolicy: RetryPolicy;
  timeoutMinutes: number;
  auditEvents: string[];
  approvalRequirements: string[];
  failureBehavior: string;
  /** Honest runtime status in the current phase. */
  runtimeStatus: CapabilityStatus;
}

const defaultRetry: RetryPolicy = {
  maxRetries: 2,
  backoff: 'exponential',
  neverRetry: ['approval decisions', 'validation verdicts', 'payments'],
};

const noRetry: RetryPolicy = { maxRetries: 0, backoff: 'none', neverRetry: ['everything — manual/escalated only'] };

export const AGENT_CATALOG: AgentDefinition[] = [
  {
    key: 'intake',
    name: 'Intake Agent',
    responsibility:
      'Receive a new website request, create the project shell, detect returning clients and existing Xability connections, and route the client into guided discovery.',
    allowedInputs: ['client request form', 'organization record', 'ecosystem connection status'],
    allowedOutputs: ['project shell', 'discovery session initialization'],
    producesArtifacts: [],
    permissionBoundaries: ['Cannot quote or promise scope, price, or timeline', 'Cannot modify billing', 'Read-only on ecosystem data'],
    requiredTools: ['project repository (data)', 'ecosystem connection reader'],
    escalationConditions: ['Duplicate active project for the same request', 'Organization in a suspended billing state'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 5,
    auditEvents: ['project.created', 'intake.completed'],
    approvalRequirements: [],
    failureBehavior: 'Abort project creation, leave no partial records, surface the error to the client with a retry option.',
    runtimeStatus: 'planned',
  },
  {
    key: 'business_discovery',
    name: 'Business Discovery Agent',
    responsibility:
      'Run guided discovery, import approved Xability business data instead of re-asking, and identify missing information for XBrain.',
    allowedInputs: ['discovery answers', 'approved Xability imports', 'business profile'],
    allowedOutputs: ['completed discovery session', 'missing-information list'],
    producesArtifacts: ['brief'],
    permissionBoundaries: ['May read only approved ecosystem data', 'Cannot invent or assume business facts', 'Cannot contact third parties'],
    requiredTools: ['discovery form engine', 'XBrain ecosystem import reader'],
    escalationConditions: ['Discovery abandoned repeatedly', 'Contradictory business information'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['discovery.updated', 'ecosystem.import.applied'],
    approvalRequirements: ['Client confirms imported Xability data before reuse'],
    failureBehavior: 'Persist partial discovery safely; never fabricate answers to complete a session.',
    runtimeStatus: 'planned',
  },
  {
    key: 'scope_analyst',
    name: 'Scope Analyst Agent',
    responsibility:
      'Convert discovery output into structured scope variables, classify the website type, and detect XApps routing candidates.',
    allowedInputs: ['discovery session', 'brief artifact'],
    allowedOutputs: ['structured scope', 'website type recommendation', 'routing assessment'],
    producesArtifacts: ['scope'],
    permissionBoundaries: ['Cannot change prices', 'Must flag — never hide — scope gaps or contradictions'],
    requiredTools: ['scope engine (@xsite/core)'],
    escalationConditions: ['XApps routing candidate detected', 'Scope contradicts discovery answers'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 15,
    auditEvents: ['scope.generated', 'scope.routing_flagged'],
    approvalRequirements: [],
    failureBehavior: 'Return the project to discovery with an explicit missing-information list.',
    runtimeStatus: 'planned',
  },
  {
    key: 'solution_architect',
    name: 'Solution Architect Agent',
    responsibility:
      'Propose the website structure, stack profile, integration map, and architecture decision record for the approved scope.',
    allowedInputs: ['scope artifact', 'supported stack profiles'],
    allowedOutputs: ['architecture decision', 'sitemap proposal', 'integration map'],
    producesArtifacts: ['sitemap', 'integration_map', 'user_journeys'],
    permissionBoundaries: ['Cannot select providers', 'Cannot start builds', 'Must stay within supported website types'],
    requiredTools: ['architecture templates', 'integration catalog'],
    escalationConditions: ['Scope requires unsupported technology', 'Conflicting integration requirements'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['architecture.proposed'],
    approvalRequirements: [],
    failureBehavior: 'Mark the architecture as unresolved and route back to the Scope Analyst with reasons.',
    runtimeStatus: 'planned',
  },
  {
    key: 'pricing',
    name: 'Pricing Agent',
    responsibility:
      'Run the rules-based pricing engine on the structured scope to produce the client quote and the separate internal breakdown.',
    allowedInputs: ['scope artifact', 'operations profile', 'pricing configuration'],
    allowedOutputs: ['client quote', 'internal cost breakdown'],
    producesArtifacts: ['quote'],
    permissionBoundaries: ['Cannot deviate from configuration or guardrails', 'Cannot expose the internal breakdown, margins, or provider costs', 'Cannot grant discounts outside configured promotions'],
    requiredTools: ['pricing engine (@xsite/core)', 'pricing configuration'],
    escalationConditions: ['requiresCustomPricing flag raised', 'Scope outside guardrail assumptions'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 5,
    auditEvents: ['quote.generated'],
    approvalRequirements: [],
    failureBehavior: 'Never emit a partial quote; fail the pricing run visibly and keep the project in Scope Review.',
    runtimeStatus: 'available',
  },
  {
    key: 'proposal',
    name: 'Proposal Agent',
    responsibility:
      'Assemble scope, quote, assumptions, and timeline into the client proposal and manage its validity window.',
    allowedInputs: ['quote artifact', 'scope artifact', 'delivery estimate'],
    allowedOutputs: ['proposal document', 'approval request'],
    producesArtifacts: [],
    permissionBoundaries: ['Cannot alter quote figures', 'Cannot mark a proposal approved — only the client approval gate can'],
    requiredTools: ['document generator', 'approval workflow'],
    escalationConditions: ['Proposal expired without decision', 'Client requests out-of-guardrail changes'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 10,
    auditEvents: ['proposal.issued', 'proposal.expired'],
    approvalRequirements: ['G1 client proposal approval'],
    failureBehavior: 'Withdraw a malformed proposal and regenerate; never leave an inconsistent proposal visible.',
    runtimeStatus: 'planned',
  },
  {
    key: 'brand_ux',
    name: 'Brand & UX Agent',
    responsibility:
      'Produce design direction, design tokens, and the layout system from brand assets (or the starter brand kit).',
    allowedInputs: ['brand assets', 'approved Xability brand data', 'sitemap artifact'],
    allowedOutputs: ['design direction candidates', 'design tokens', 'component inventory'],
    producesArtifacts: ['design_tokens', 'component_inventory'],
    permissionBoundaries: ['Cannot apply a direction without client approval', 'Cannot use unlicensed assets'],
    requiredTools: ['DesignProvider adapter', 'asset storage'],
    escalationConditions: ['No usable brand assets and starter kit rejected twice'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 60,
    auditEvents: ['design.direction_proposed'],
    approvalRequirements: ['G3 client design approval'],
    failureBehavior: 'Present the failure and fall back to curated direction templates for client choice.',
    runtimeStatus: 'planned',
  },
  {
    key: 'content',
    name: 'Content Agent',
    responsibility:
      'Define the content model and draft page content, reusing approved Xability content where available.',
    allowedInputs: ['brief', 'scope', 'approved Xability content', 'brand voice'],
    allowedOutputs: ['content model', 'content drafts'],
    producesArtifacts: ['content_model', 'page_specification'],
    permissionBoundaries: ['Truthful content only — no fabricated claims, statistics, or testimonials', 'Nothing publishes without client approval'],
    requiredTools: ['ContentProvider adapter', 'content storage'],
    escalationConditions: ['Client-provided facts unverifiable or contradictory'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 60,
    auditEvents: ['content.drafted'],
    approvalRequirements: ['Client approval before any content is published'],
    failureBehavior: 'Deliver partial drafts marked as drafts; never silently substitute invented content.',
    runtimeStatus: 'planned',
  },
  {
    key: 'seo_geo',
    name: 'SEO & GEO Agent',
    responsibility:
      'Produce the technical SEO plan (metadata, canonicals, sitemap, robots, structured data, internal linking, redirects) and GEO readiness (entity definitions, direct answers, semantic HTML, truthful FAQ), then monitor both in operations.',
    allowedInputs: ['sitemap', 'content model', 'analytics data', 'search console data'],
    allowedOutputs: ['SEO plan', 'GEO readiness plan', 'monitoring reports', 'recommendations'],
    producesArtifacts: ['seo_plan'],
    permissionBoundaries: ['Never promises rankings, traffic, citations, or AI-answer placement', 'Cannot apply site changes directly — changes go through the build/change pipeline'],
    requiredTools: ['SeoProvider adapter', 'Search Console connection'],
    escalationConditions: ['Indexation collapse or manual action detected'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['seo.plan_generated', 'seo.issue_detected'],
    approvalRequirements: [],
    failureBehavior: 'Report monitoring gaps honestly rather than showing stale data as fresh.',
    runtimeStatus: 'planned',
  },
  {
    key: 'build_orchestrator',
    name: 'Technical Build Orchestrator',
    responsibility:
      'Decompose the approved scope into isolated tasks with acceptance criteria, dependencies, and budgets; create the repository and branch structure; sequence the pipeline.',
    allowedInputs: ['approved scope', 'architecture decision', 'design tokens', 'content model'],
    allowedOutputs: ['task graph', 'repository', 'branch plan'],
    producesArtifacts: ['acceptance_criteria', 'test_plan', 'deployment_plan'],
    permissionBoundaries: ['Cannot execute code changes itself', 'Cannot skip validation stages', 'Cannot exceed the project provider budget'],
    requiredTools: ['RepositoryProvider adapter', 'task queue'],
    escalationConditions: ['Task graph cannot satisfy dependencies', 'Budget insufficient for decomposed tasks'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['build.tasks_created', 'repository.created'],
    approvalRequirements: [],
    failureBehavior: 'Halt before execution with an explicit blocker list; never start a partial pipeline.',
    runtimeStatus: 'planned',
  },
  {
    key: 'coding_provider',
    name: 'Coding Provider Agent',
    responsibility:
      'Execute exactly one isolated task through a CodingProvider adapter on a task-scoped branch, within cost and time budgets.',
    allowedInputs: ['task with acceptance criteria', 'branch-scoped repo credentials', 'prompt template (versioned)'],
    allowedOutputs: ['branch diff', 'execution report'],
    producesArtifacts: [],
    permissionBoundaries: ['Branch-scoped only — no access to main/production', 'Budget-capped (P5)', 'Output goes only to validation, never to production', 'No platform secrets or other tenants'],
    requiredTools: ['CodingProvider adapter (Claude Code, OpenAI Codex, future providers)'],
    escalationConditions: ['Budget exhausted', 'Provider circuit breaker open', 'Repeated validation failure on the same task'],
    retryPolicy: { maxRetries: 2, backoff: 'exponential', neverRetry: ['tasks whose budget is exhausted'] },
    timeoutMinutes: 45,
    auditEvents: ['provider.execution_started', 'provider.execution_completed', 'provider.execution_failed'],
    approvalRequirements: [],
    failureBehavior: 'Abandon the branch untouched-by-merge, record the failure, trigger fallback provider selection.',
    runtimeStatus: 'planned',
  },
  {
    key: 'code_review',
    name: 'Code Review Agent',
    responsibility:
      'Automatically review provider output against acceptance criteria, coding standards, and diff hygiene before anything merges.',
    allowedInputs: ['branch diff', 'acceptance criteria', 'standards profile'],
    allowedOutputs: ['review verdict', 'required-change list'],
    producesArtifacts: [],
    permissionBoundaries: ['Cannot approve its own changes', 'Cannot mark failed checks as passed', 'Verdicts are immutable'],
    requiredTools: ['ReasoningProvider adapter', 'static analysis'],
    escalationConditions: ['Same task fails review 3 times'],
    retryPolicy: noRetry,
    timeoutMinutes: 20,
    auditEvents: ['review.verdict'],
    approvalRequirements: [],
    failureBehavior: 'A review that cannot complete counts as a failed review, never as a pass.',
    runtimeStatus: 'planned',
  },
  {
    key: 'qa',
    name: 'QA Agent',
    responsibility: 'Run functional, integration, and E2E tests and record immutable verdicts.',
    allowedInputs: ['staging build', 'test plan artifact'],
    allowedOutputs: ['test results', 'defect reports'],
    producesArtifacts: [],
    permissionBoundaries: ['Cannot waive failing tests', 'Cannot edit application code'],
    requiredTools: ['CiProvider adapter', 'test runners'],
    escalationConditions: ['Flaky infrastructure prevents any verdict', 'Repeated failures beyond retry policy'],
    retryPolicy: { maxRetries: 1, backoff: 'linear', neverRetry: ['failed assertions (only infrastructure flakes retry)'] },
    timeoutMinutes: 45,
    auditEvents: ['qa.run_completed'],
    approvalRequirements: [],
    failureBehavior: 'Failures block the pipeline (P1); no green-washing under any condition.',
    runtimeStatus: 'planned',
  },
  {
    key: 'accessibility',
    name: 'Accessibility Agent',
    responsibility: "Check every deliverable against the project's declared accessibility level.",
    allowedInputs: ['staging build', 'declared accessibility level'],
    allowedOutputs: ['accessibility report', 'violation list'],
    producesArtifacts: [],
    permissionBoundaries: ['Cannot lower the declared level', 'Cannot waive violations'],
    requiredTools: ['accessibility scanners'],
    escalationConditions: ['Violations persist after retries'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 20,
    auditEvents: ['accessibility.report'],
    approvalRequirements: [],
    failureBehavior: 'Blocking violations keep the pipeline red until fixed.',
    runtimeStatus: 'planned',
  },
  {
    key: 'security',
    name: 'Security Agent',
    responsibility: 'Dependency, secret-leak, and configuration security checks on every build.',
    allowedInputs: ['branch diff', 'dependency manifest', 'infrastructure config'],
    allowedOutputs: ['security report', 'block verdicts'],
    producesArtifacts: [],
    permissionBoundaries: ['Can block the pipeline', 'Cannot disable security controls', 'Cannot exfiltrate or log secret values'],
    requiredTools: ['dependency scanners', 'secret scanners'],
    escalationConditions: ['Critical vulnerability or leaked credential found'],
    retryPolicy: noRetry,
    timeoutMinutes: 20,
    auditEvents: ['security.scan_completed', 'security.block'],
    approvalRequirements: [],
    failureBehavior: 'On scanner failure the check is inconclusive → pipeline stays blocked (fail closed).',
    runtimeStatus: 'planned',
  },
  {
    key: 'performance',
    name: 'Performance Agent',
    responsibility: "Enforce performance budgets against the project's declared target.",
    allowedInputs: ['staging build', 'performance target'],
    allowedOutputs: ['performance report'],
    producesArtifacts: [],
    permissionBoundaries: ['Cannot waive budgets silently'],
    requiredTools: ['performance testing tools'],
    escalationConditions: ['Budget cannot be met within the approved architecture'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 20,
    auditEvents: ['performance.report'],
    approvalRequirements: [],
    failureBehavior: 'Failing budgets block; any waiver is an explicit, audited client-visible decision.',
    runtimeStatus: 'planned',
  },
  {
    key: 'integration',
    name: 'Integration Agent',
    responsibility:
      'Configure and verify integrations (Meta Pixel, GA4, GTM, Search Console, Google Business Profile, Google Ads, Clarity, CRM, email, WhatsApp, maps, booking, payment gateways, Xability) with health checks and error history.',
    allowedInputs: ['integration requests', 'non-secret config', 'secret references'],
    allowedOutputs: ['integration status', 'verification results', 'health reports'],
    producesArtifacts: ['integration_map'],
    permissionBoundaries: ['Secrets by reference only — never reads raw secret values into logs or UI', 'Account-level connections require client confirmation', 'Cannot fabricate a verified status'],
    requiredTools: ['AnalyticsProvider / integration adapters', 'secret store'],
    escalationConditions: ['Verification fails repeatedly', 'Provider-side permission revoked'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 20,
    auditEvents: ['integration.connected', 'integration.verified', 'integration.error', 'integration.disconnected'],
    approvalRequirements: ['Client confirmation for account-level connections and disconnects'],
    failureBehavior: 'Mark the integration errored with visible history; never report healthy without a passing check.',
    runtimeStatus: 'planned',
  },
  {
    key: 'deployment',
    name: 'Deployment Agent',
    responsibility: 'Execute staging and production deployments, smoke tests, rollbacks, and deployment locks.',
    allowedInputs: ['validated build', 'deployment plan', 'gate status'],
    allowedOutputs: ['deployments', 'smoke results', 'rollbacks'],
    producesArtifacts: [],
    permissionBoundaries: ['Production deploys only with G5+G6+P1+P2 satisfied', 'Cannot delete environments', 'Cannot deploy unvalidated builds'],
    requiredTools: ['DeploymentProvider adapter', 'HostingProvider adapter'],
    escalationConditions: ['Smoke tests fail after rollback', 'Provider outage mid-deploy'],
    retryPolicy: { maxRetries: 1, backoff: 'linear', neverRetry: ['deploys that failed validation'] },
    timeoutMinutes: 30,
    auditEvents: ['deployment.started', 'deployment.completed', 'deployment.rolled_back'],
    approvalRequirements: ['G6 client deployment approval'],
    failureBehavior: 'Automatic rollback to the last good deployment; incident opened if rollback fails.',
    runtimeStatus: 'planned',
  },
  {
    key: 'domain_dns',
    name: 'Domain & DNS Agent',
    responsibility: 'Domain verification, DNS records, TLS issuance, and safe cut-overs.',
    allowedInputs: ['domain records', 'verification tokens', 'client confirmations'],
    allowedOutputs: ['DNS changes', 'verification status'],
    producesArtifacts: [],
    permissionBoundaries: ['NEVER transfers a domain without explicit client confirmation (P3)', 'Cannot modify records outside the project domain'],
    requiredTools: ['DnsProvider adapter'],
    escalationConditions: ['Ownership verification fails', 'Propagation anomalies'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['domain.verified', 'dns.updated', 'domain.transfer_confirmed'],
    approvalRequirements: ['Explicit client confirmation for transfers and cut-overs'],
    failureBehavior: 'Leave existing DNS untouched on any failure; never leave a domain half-migrated.',
    runtimeStatus: 'planned',
  },
  {
    key: 'analytics',
    name: 'Analytics Agent',
    responsibility: 'Wire analytics properties, validate data quality, and produce measurement dashboards.',
    allowedInputs: ['analytics config', 'traffic data'],
    allowedOutputs: ['dashboards', 'data-quality reports'],
    producesArtifacts: [],
    permissionBoundaries: ['Read/report only', 'No data sharing beyond policy', 'No PII collection beyond configured consent'],
    requiredTools: ['AnalyticsProvider adapter'],
    escalationConditions: ['Tracking loss detected'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 20,
    auditEvents: ['analytics.configured', 'analytics.issue_detected'],
    approvalRequirements: [],
    failureBehavior: 'Report measurement gaps explicitly; never interpolate missing data as real.',
    runtimeStatus: 'planned',
  },
  {
    key: 'client_success',
    name: 'Client Success Agent',
    responsibility:
      'Guide onboarding, request missing information, explain status/delays/invoices, collect approvals, send reminders, summarize changes, deliver monthly reports, recommend next HorizonX products, detect dissatisfaction, and open incident workflows.',
    allowedInputs: ['project state', 'approval queue', 'billing summaries', 'report artifacts'],
    allowedOutputs: ['client messages', 'reminders', 'reports', 'incident triggers'],
    producesArtifacts: [],
    permissionBoundaries: ['ALWAYS identifies itself as the XSite AI project manager — never claims to be human', 'No manipulative sales behavior', 'Cannot approve anything on the client’s behalf', 'Cannot change prices or scope'],
    requiredTools: ['EmailProvider / MessagingProvider adapters', 'notification system'],
    escalationConditions: ['Detected dissatisfaction or repeated failures', 'Unanswered critical approval past SLA'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 10,
    auditEvents: ['client.message_sent', 'client.reminder_sent', 'client.escalation_opened'],
    approvalRequirements: [],
    failureBehavior: 'Missed communications are queued and flagged, never silently dropped.',
    runtimeStatus: 'planned',
  },
  {
    key: 'change_request',
    name: 'Change Request Agent',
    responsibility:
      'Understand a post-launch request, identify the affected area, classify it (included / overage / new scope), estimate cost and risk, generate acceptance criteria, obtain approval when billable, then drive isolated execution, validation, preview, approval, deployment, and usage recording.',
    allowedInputs: ['change requests (conversational or form)', 'plan allowance state', 'website map'],
    allowedOutputs: ['classified requests', 'estimates', 'execution tasks', 'usage records'],
    producesArtifacts: ['acceptance_criteria'],
    permissionBoundaries: ['Fair-usage limits enforced from config', 'Billable work requires G7 approval BEFORE execution', 'Executes only through the standard validated pipeline'],
    requiredTools: ['scope engine (classification)', 'task pipeline', 'usage metering'],
    escalationConditions: ['Request is new project scope', 'Risk estimate high'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['change_request.classified', 'change_request.approved', 'change_request.deployed', 'usage.recorded'],
    approvalRequirements: ['G7 client approval for billable requests'],
    failureBehavior: 'Failed changes roll back their branch and deployment; the client is informed with the reason.',
    runtimeStatus: 'planned',
  },
  {
    key: 'website_operations',
    name: 'Website Operations Agent',
    responsibility: 'Uptime and health monitoring, verified backups, routine maintenance, and content operations for live websites.',
    allowedInputs: ['monitoring signals', 'backup schedules', 'maintenance windows'],
    allowedOutputs: ['health reports', 'maintenance runs', 'backup verifications'],
    producesArtifacts: ['operations_plan'],
    permissionBoundaries: ['Cannot delete production resources', 'Destructive operations require policy + client confirmation', 'Maintenance changes go through the validated pipeline'],
    requiredTools: ['MonitoringProvider adapter', 'backup tooling'],
    escalationConditions: ['Backup verification fails', 'Sustained degradation'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['operations.maintenance_run', 'backup.verified', 'backup.failed'],
    approvalRequirements: ['Client confirmation for any destructive operation'],
    failureBehavior: 'An unverified backup counts as no backup and raises an alert.',
    runtimeStatus: 'planned',
  },
  {
    key: 'billing_usage',
    name: 'Billing & Usage Agent',
    responsibility: 'Invoices, usage metering, overage calculation, and subscription lifecycle (start at go-live, plan changes, dunning).',
    allowedInputs: ['pricing config', 'usage records', 'payment provider events'],
    allowedOutputs: ['invoices', 'usage summaries', 'subscription state changes'],
    producesArtifacts: [],
    permissionBoundaries: ['Prices only from central config', 'NO silent billing modifications — every change is notified and audited', 'Refunds/credits above threshold escalate', 'Idempotent against duplicate payment events'],
    requiredTools: ['PaymentProvider adapter', 'usage metering'],
    escalationConditions: ['Payment disputes', 'Repeated payment failures', 'Refund above threshold'],
    retryPolicy: { maxRetries: 3, backoff: 'exponential', neverRetry: ['charges that received a definitive decline'] },
    timeoutMinutes: 15,
    auditEvents: ['invoice.issued', 'payment.recorded', 'subscription.started', 'subscription.changed', 'overage.recorded'],
    approvalRequirements: ['Client approval for plan changes and overage billing beyond pre-approved allowances'],
    failureBehavior: 'Billing uncertainty always resolves in favor of not charging until reconciled.',
    runtimeStatus: 'planned',
  },
  {
    key: 'incident_response',
    name: 'Incident Response Agent',
    responsibility: 'Detect incidents, open incident state, mitigate with reversible actions (rollback first), and keep the client informed.',
    allowedInputs: ['monitoring alerts', 'deployment history', 'incident reports'],
    allowedOutputs: ['incident records', 'mitigations', 'status communications'],
    producesArtifacts: [],
    permissionBoundaries: ['Mitigation limited to reversible actions', 'Irreversible fixes require approval', 'Cannot suppress or edit incident history'],
    requiredTools: ['MonitoringProvider adapter', 'Deployment rollback'],
    escalationConditions: ['Rollback does not resolve', 'Security incident suspected'],
    retryPolicy: { maxRetries: 1, backoff: 'none', neverRetry: ['mitigations that made things worse'] },
    timeoutMinutes: 15,
    auditEvents: ['incident.opened', 'incident.mitigated', 'incident.resolved'],
    approvalRequirements: ['Approval for irreversible remediation'],
    failureBehavior: 'If mitigation fails, freeze changes, keep the incident open and visible, escalate.',
    runtimeStatus: 'planned',
  },
  {
    key: 'compliance_audit',
    name: 'Compliance & Audit Agent',
    responsibility:
      'Continuously check policy conformance over the audit stream, enforce retention rules, and operate the export and cancellation workflows.',
    allowedInputs: ['audit events', 'policy definitions', 'retention rules'],
    allowedOutputs: ['conformance reports', 'policy violation flags', 'export packages'],
    producesArtifacts: [],
    permissionBoundaries: ['Read-only over other contexts', 'Can freeze (flag) but not modify', 'Cannot delete audit events — ever'],
    requiredTools: ['audit store reader', 'export tooling'],
    escalationConditions: ['Policy violation detected', 'Retention conflict'],
    retryPolicy: defaultRetry,
    timeoutMinutes: 30,
    auditEvents: ['compliance.check_completed', 'compliance.violation_flagged', 'export.completed'],
    approvalRequirements: ['Client confirmation for cancellation and data deletion (P4)'],
    failureBehavior: 'A failed conformance check blocks the affected workflow rather than passing silently.',
    runtimeStatus: 'planned',
  },
];

export function getAgent(key: string): AgentDefinition | undefined {
  return AGENT_CATALOG.find((a) => a.key === key);
}

export const AGENT_COUNT = AGENT_CATALOG.length;
