'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { buildProposal, buildSolutionBrief, qualificationLabel } from '@/lib/sales-intelligence';
import { createDealFromLead, loadSalesState, serviceLabel, updateLead } from '@/lib/sales-store';
import type { Lead } from '@/lib/sales-types';

export default function LeadWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState('');
  const [lead, setLead] = useState<Lead | null>(null);
  const [price, setPrice] = useState(0);
  useEffect(() => { params.then(({ id: value }) => { setId(value); const found = loadSalesState().leads.find((item) => item.id === value) || null; setLead(found); setPrice(found?.estimatedValue || 1000); }); }, [params]);
  const brief = useMemo(() => lead ? buildSolutionBrief(lead) : null, [lead]);
  const proposal = useMemo(() => lead ? buildProposal(lead, price) : null, [lead, price]);
  if (!lead || !brief || !proposal) return <div><Link href="/sales">← Sales</Link><p className="mt-8 text-slate-500">{id ? 'Lead not found.' : 'Loading lead…'}</p></div>;
  const saveStatus = (status: Lead['status']) => { updateLead(lead.id, { status }); setLead({ ...lead, status }); };
  const dates = [0, 14, 28, 35].map((days) => { const d = new Date(); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10); });
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/sales" className="text-sm text-slate-500">← Sales command center</Link><h1 className="mt-2 text-3xl font-black">{lead.businessName}</h1><p className="text-slate-500">{serviceLabel(lead.service)} · {lead.contactName} · {lead.country}{lead.city ? ` / ${lead.city}` : ''}</p></div><div className="rounded-2xl bg-orange-500/10 px-5 py-3 text-center"><p className="text-xs font-bold uppercase text-orange-500">{qualificationLabel(lead.score)}</p><p className="text-3xl font-black text-orange-500">{lead.score}/100</p></div></div>
  <div className="grid gap-5 lg:grid-cols-3"><section className="card lg:col-span-2"><h2 className="text-xl font-black">AI-ready solution brief</h2><p className="mt-1 text-xs text-slate-400">Deterministic MVP brief; external model enhancement can be connected later.</p><h3 className="mt-5 font-bold">{brief.title}</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{brief.summary}</p><h3 className="mt-5 text-sm font-bold">Recommended scope</h3><ul className="mt-2 list-disc space-y-1 ps-5 text-sm text-slate-600 dark:text-slate-400">{brief.deliverables.map((item) => <li key={item}>{item}</li>)}</ul><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info label="Implementation" value={brief.implementation}/><Info label="Internal range" value={`${brief.commercialRange.min.toLocaleString()}–${brief.commercialRange.max.toLocaleString()} JOD`}/><Info label="Confidence" value={`${brief.confidence}%`}/></div><h3 className="mt-5 text-sm font-bold">Questions before final approval</h3><ul className="mt-2 list-disc ps-5 text-sm text-slate-500">{brief.questions.map((q) => <li key={q}>{q}</li>)}</ul></section>
  <section className="card"><h2 className="font-black">Lead controls</h2><label className="mt-4 block text-xs text-slate-500">Pipeline stage</label><select value={lead.status} onChange={(e) => saveStatus(e.target.value as Lead['status'])} className="input mt-1"><option value="new">New</option><option value="qualified">Qualified</option><option value="needs_clarification">Needs clarification</option><option value="solution_ready">Solution ready</option><option value="proposal_sent">Proposal sent</option><option value="negotiation">Negotiation</option><option value="won">Won</option><option value="lost">Lost</option></select><div className="mt-5 space-y-2 text-sm"><p><b>Phone:</b> {lead.phone}</p><p><b>WhatsApp:</b> {lead.whatsapp}</p>{lead.email && <p><b>Email:</b> {lead.email}</p>}<p><b>Budget:</b> {lead.budget}</p><p><b>Timeline:</b> {lead.timeline}</p><p><b>Source:</b> {lead.source}</p></div></section></div>
  <section className="card"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-orange-500">Proposal builder</p><h2 className="text-xl font-black">{proposal.title}</h2></div><div className="flex items-end gap-2"><label className="text-xs text-slate-500">Final price<input type="number" value={price} onChange={(e) => setPrice(Number(e.target.value))} className="input mt-1 w-36" /></label><button onClick={() => saveStatus('proposal_sent')} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold dark:border-slate-700">Mark proposal sent</button><button onClick={() => { createDealFromLead(lead, price, dates); setLead({ ...lead, status: 'won' }); }} className="rounded-lg bg-orange-500 px-4 py-2 text-sm font-black text-black">Accept & create deal</button></div></div><p className="mt-5 max-w-3xl text-sm text-slate-600 dark:text-slate-400">{proposal.executiveSummary}</p><div className="mt-5 grid gap-5 md:grid-cols-3"><div><h3 className="font-bold">Deliverables</h3>{proposal.scope.map((item) => <p key={item} className="mt-1 text-sm text-slate-500">✓ {item}</p>)}</div><div><h3 className="font-bold">Timeline</h3><p className="mt-1 text-sm text-slate-500">{proposal.timeline}</p><h3 className="mt-4 font-bold">Investment</h3><p className="mt-1 text-2xl font-black">{proposal.investment.toLocaleString()} JOD</p></div><div><h3 className="font-bold">Payment schedule</h3>{proposal.paymentPlan.map((pct, i) => <p key={pct} className="mt-1 text-sm text-slate-500">{i + 1}. {pct}% — {(price * pct / 100).toLocaleString()} JOD</p>)}</div></div></section>
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
