'use client';

import { FormEvent, useState } from 'react';
import { addLead, budgetMidpoint, scoreLead } from '@/lib/sales-store';
import type { Lead, ServiceType } from '@/lib/sales-types';

export default function ProspectingPage() {
  const [message, setMessage] = useState('');
  const [form, setForm] = useState({ businessName: '', contactName: '', phone: '', email: '', website: '', country: 'Jordan', city: '', industry: '', service: 'website' as ServiceType, opportunity: '', sourceUrl: '' });
  const set = (key: keyof typeof form, value: string) => setForm((prev) => ({ ...prev, [key]: value }));
  function submit(e: FormEvent) { e.preventDefault(); const base = { budget: 'Not sure', timeline: 'No fixed deadline', problem: form.opportunity || 'Outbound prospect identified for digital improvement.', service: form.service }; const lead: Lead = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), businessName: form.businessName, contactName: form.contactName || 'Unknown', phone: form.phone, whatsapp: form.phone, email: form.email || undefined, country: form.country, city: form.city || undefined, industry: form.industry || undefined, service: form.service, goal: 'Outbound digital opportunity', problem: base.problem, currentWorkflow: form.website ? `Website: ${form.website}` : undefined, budget: base.budget, timeline: base.timeline, source: form.sourceUrl || 'manual_prospecting', status: 'new', score: Math.max(35, scoreLead(base) - 15), estimatedValue: budgetMidpoint(base.budget), nextAction: 'Research business and validate opportunity before outreach' }; addLead(lead); setMessage(`${lead.businessName} added to CRM.`); setForm({ ...form, businessName: '', contactName: '', phone: '', email: '', website: '', opportunity: '', sourceUrl: '' }); }
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-500">Lead engine</p><h1 className="mt-1 text-3xl font-black">Prospecting</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Capture a business found on Google Maps, a directory, social media or a public website. The MVP stores the source and opportunity; automated compliant discovery providers plug into this workspace later.</p></div>{message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{message}</div>}<form onSubmit={submit} className="card grid gap-4 sm:grid-cols-2"><input required value={form.businessName} onChange={(e) => set('businessName', e.target.value)} placeholder="Business name" className="input"/><input value={form.industry} onChange={(e) => set('industry', e.target.value)} placeholder="Industry" className="input"/><input value={form.country} onChange={(e) => set('country', e.target.value)} placeholder="Country" className="input"/><input value={form.city} onChange={(e) => set('city', e.target.value)} placeholder="City" className="input"/><input value={form.website} onChange={(e) => set('website', e.target.value)} placeholder="Website" className="input"/><input value={form.sourceUrl} onChange={(e) => set('sourceUrl', e.target.value)} placeholder="Public source URL" className="input"/><input value={form.contactName} onChange={(e) => set('contactName', e.target.value)} placeholder="Public contact name (optional)" className="input"/><input value={form.phone} onChange={(e) => set('phone', e.target.value)} placeholder="Public phone" className="input"/><input type="email" value={form.email} onChange={(e) => set('email', e.target.value)} placeholder="Public business email" className="input"/><select value={form.service} onChange={(e) => setForm((prev) => ({ ...prev, service: e.target.value as ServiceType }))} className="input"><option value="website">Website</option><option value="app">App</option><option value="business_system">Business system</option><option value="ai_solution">AI solution</option><option value="ecommerce">E-commerce</option><option value="crm">CRM</option><option value="recommend">Needs discovery</option></select><textarea required value={form.opportunity} onChange={(e) => set('opportunity', e.target.value)} placeholder="Why is this business an opportunity? Example: outdated site, no lead capture, manual WhatsApp workflow..." className="input min-h-28 sm:col-span-2"/><button className="rounded-xl bg-orange-500 px-5 py-3 font-black text-black sm:col-span-2">Add prospect to CRM</button></form></div>;
}
